### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by g-oncharov** [g-oncharov/homepage#4]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by gonchxrov** [comment]
### ― I do not compete with others, the only competition that challenges me is myself. As a fighter, friend and an employee I am known as contemplative, tortured and driven.

**Comment by gonchxrov** [comment]
― I do not compete with others, the only competition that challenges me is myself &#129355;.
A fighter with the techniques of Hadoken &#127744;, Shoryuken &#128165; and Tatsumaki Senpukyaku &#128171;
